### ISSUE TITLE
Storage

### ISSUE THREAD

**Issue by alanbluwol** [alanbluwol/SEBC#3]

**Comment by mfernest** [comment]
Replication - good documentation of what did not work. What would you try next?

**Comment by mfernest** [comment]
Interesting that your `terasort` resulted in six output files. Did you expect that?

**Comment by mfernest** [comment]
Deleting a directory that is also a snapshot location should not work. What went wrong here?

**Comment by mfernest** [comment]
I appreciate all the attention to detail you gave here. It not only shows good work, it exposes small errors very well -- that's a good thing!
